# -*- coding: utf-8 -*-
"""Dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139IqL0_XCD1KevhWfgRrv__V6RRB3NvI
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
path = '/content/drive/MyDrive/AI/AI/data sheet.xlsx'


try:
    df = pd.read_excel(path)


    print("Shape of the DataFrame:")
    print(df.shape)

    print("\nColumns of the DataFrame:")
    print(df.columns)


    print("\nInformation about the DataFrame:")
    df.info()


    print("\nFirst 5 rows of the DataFrame:")
    display(df.head())

except FileNotFoundError:
    print(f"Error: The file was not found at {path}")
except Exception as e:
    print(f"An error occurred: {e}")

# Inspect the first few rows to identify the correct header row
display(df.head(10))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
path = '/content/drive/MyDrive/AI/Test_data.csv'

df = pd.read_csv(path)
#df.head()
print(df.shape)
print(df.columns)
print(df.describe())
#df.Info





"""# Task
Generate a line chart, a histogram or distribution plot, and a bar chart using Matplotlib based on the columns of the dataframe.

## Identify columns for plotting

### Subtask:
Determine which columns from the DataFrame are suitable for creating line, histogram/distribution, and bar charts based on their data types and content.

**Reasoning**:
Inspect the data types and a few unique values of each column to determine suitability for different plot types.
"""

print(df.dtypes)
for column in df.columns:
    print(f"\nColumn: {column}")
    print(f"Number of unique values: {df[column].nunique()}")
    if df[column].nunique() < 20: # Display unique values for columns with few unique values
        print(f"Unique values: {df[column].unique()}")
    else:
        print(f"First 5 unique values: {df[column].unique()[:5]}")

"""## Generate code for line chart

### Subtask:
Create a code cell to generate a line chart using Matplotlib, using the selected columns.

**Reasoning**:
Generate a line chart for the 'src_bytes' column against the DataFrame index.
"""

plt.figure(figsize=(12, 6))
plt.plot(df.index, df['src_bytes'])
plt.xlabel('Index')
plt.ylabel('src_bytes')
plt.title('Line Chart of src_bytes')
plt.show()

"""## Generate code for histogram/distribution plot

### Subtask:
Create a code cell to generate a histogram or a similar distribution plot using Matplotlib, using the selected columns.

**Reasoning**:
Generate a histogram for the 'duration' column to visualize its distribution.
"""

plt.figure()
plt.hist(df['duration'])
plt.xlabel('Duration')
plt.ylabel('Frequency')
plt.title('Distribution of Duration')
plt.show()

"""## Generate code for bar chart

### Subtask:
Create a code cell to generate a bar chart using Matplotlib, using the selected columns.

**Reasoning**:
Calculate the value counts for 'protocol_type' and generate a bar chart based on these counts as instructed.
"""

plt.figure()
protocol_counts = df['protocol_type'].value_counts()
plt.bar(protocol_counts.index, protocol_counts.values)
plt.xlabel('Protocol Type')
plt.ylabel('Count')
plt.title('Distribution of Protocol Types')
plt.show()

"""## Explain the generated code

### Subtask:
Provide explanations for the code used to generate the line chart, histogram, and bar chart.

**Reasoning**:
Explain the code for generating the line chart, histogram, and bar chart as requested in the instructions.
"""

print("Explanation for Line Chart ('Line Chart of src_bytes'):")
print("plt.figure(figsize=(12, 6)): This line creates a new figure for the plot with a specified size of 12 inches in width and 6 inches in height. This helps in adjusting the overall size of the plot.")
print("plt.plot(df.index, df['src_bytes']): This is the core line for generating the line chart. It plots the values from the 'src_bytes' column against the DataFrame's index. The DataFrame index is used as the x-axis because there isn't a specific time-series column, representing the order of the data points. 'src_bytes' values are plotted on the y-axis, showing how the source bytes change across the dataset's entries.")
print("plt.xlabel('Index'): This sets the label for the x-axis to 'Index'.")
print("plt.ylabel('src_bytes'): This sets the label for the y-axis to 'src_bytes'.")
print("plt.title('Line Chart of src_bytes'): This sets the title of the line chart to 'Line Chart of src_bytes'.")
print("plt.show(): This displays the generated plot.")

print("\nExplanation for Histogram ('Distribution of Duration'):")
print("plt.figure(): This creates a new figure for the histogram.")
print("plt.hist(df['duration']): This generates the histogram. It takes the 'duration' column as input and automatically divides the data into bins, counting how many values fall into each bin. The height of each bar in the histogram represents the frequency (count) of data points within that bin.")
print("plt.xlabel('Duration'): This sets the label for the x-axis to 'Duration', representing the range of values for the duration of connections.")
print("plt.ylabel('Frequency'): This sets the label for the y-axis to 'Frequency', indicating the number of data points that fall within each duration range bin.")
print("plt.title('Distribution of Duration'): This sets the title of the histogram to 'Distribution of Duration'.")
print("plt.show(): This displays the generated plot. From this histogram, we can understand the distribution of connection durations, identifying common durations and the spread of the data.")

print("\nExplanation for Bar Chart ('Distribution of Protocol Types'):")
print("plt.figure(): This creates a new figure for the bar chart.")
print("protocol_counts = df['protocol_type'].value_counts(): This line calculates the frequency of each unique value in the 'protocol_type' column. It returns a pandas Series where the index represents the unique protocol types and the values are their corresponding counts. This is the data that will be used to create the bars.")
print("plt.bar(protocol_counts.index, protocol_counts.values): This is the core line for generating the bar chart. It creates bars where the x-positions are the unique protocol types (from the index of protocol_counts) and the height of each bar is the count of that protocol type (from the values of protocol_counts).")
print("plt.xlabel('Protocol Type'): This sets the label for the x-axis to 'Protocol Type'.")
print("plt.ylabel('Count'): This sets the label for the y-axis to 'Count', representing the number of occurrences for each protocol type.")
print("plt.title('Distribution of Protocol Types'): This sets the title of the bar chart to 'Distribution of Protocol Types'. This visualization helps in understanding the most frequent protocol types in the dataset.")
print("plt.show(): This displays the generated plot.")

"""## Summary:

### Data Analysis Key Findings

*   The dataset contains a mix of numerical (`int64`, `float64`) and categorical (`object`) columns.
*   Several columns have a small number of unique values (e.g., `protocol_type`, `land`, `logged_in`), making them suitable for bar charts.
*   Numerical columns like `duration`, `src_bytes`, and `dst_bytes` have a wide range of unique values, suitable for histograms.
*   A line chart of `src_bytes` was generated against the DataFrame index as a proxy for a time-series plot.
*   A histogram of the `duration` column was successfully created, showing the distribution of connection durations.
*   A bar chart showing the distribution of `protocol_type` was generated, indicating the frequency of each protocol type.

### Insights or Next Steps

*   The generated plots provide initial visual insights into the distribution of numerical features and the frequency of categorical features.
*   Further analysis could involve exploring the relationships between different columns using scatter plots or other multivariate visualizations.

"""